export const metadata = {
    title: {
        absolute:'',
        default:"Sujit is King",
        templete:""
    },
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    )
  }